name: 'Set approved label and automerge'
description: 'Set approved label and automerge'
inputs:
   GITHUB_TOKEN:
      description: 'Github token'
      required: true
   required_approves:
      description: 'Number of ok reviews'
      required: false
      default: '3'
runs:
   using: 'docker'
   image: 'Dockerfile'
   args:
      - ${{ inputs.GITHUB_TOKEN }}
      - ${{ inputs.required_approves }}
branding:
   icon: 'tag'
   color: 'green'
